export const data = [
  {
    id: 1,
    img: "/static/cover/cover.jpg",
    imgCover: "/static/home/home__bg.jpg",
    alt: "cover",
    href: "/",
    title: "من به زبان دیگری خواب می بینم",
    category: { genre: "Action", triler: "triler" },
    rate: 8.4,
  },
  {
    id: 2,
    img: "/static/cover/cover1.jpg",
    imgCover: "/static/home/home__bg2.jpg",
    alt: "cover1",
    href: "/",
    title: "نیمکت نشین",
    category: { genre: "Action" },
    rate: 6.4,
  },
  {
    id: 3,
    img: "/static/cover/cover2.jpg",
    imgCover: "/static/home/home__bg3.jpg",
    alt: "cover2",
    href: "/",
    title: "ویتنی",
    category: { genre: "Action", triler: "triler" },
    rate: 9.4,
  },
  {
    id: 4,
    img: "/static/cover/cover3.jpg",
    imgCover: "/static/home/home__bg4.jpg",
    alt: "cover3",
    href: "/",
    title: "نقطه کور",
    rate: 6.6,
    category: { genre: "Action", triler: "triler" },
  },
  {
    id: 5,
    img: "/static/cover/cover4.jpg",
    imgCover: "/static/home/home__bg5.jpg",
    alt: "cover4",
    href: "/",
    title: "نقطه کور",
    rate: 7.4,
    category: { genre: "Action", triler: "triler" },
  },
  {
    id: 6,
    img: "/static/cover/cover5.jpg",
    imgCover: "/static/home/home__bg2.jpg",
    alt: "cover5",
    href: "/",
    title: "من به زبان دیگری خواب می بینم",
    rate: 8.4,
    category: { genre: "Action" },
  },
];
