export const optionsGenre = [
  { value: "action/adventure", label: "اکشن/ماجراجویی" },
  { value: "animals", label: "حیوانات" },
  { value: "animation", label: "انیمیشن" },
  { value: "biography", label: "زندگینامه" },
  { value: "comedy", label: "کمدی" },
  { value: "cooking", label: "پخت و پز" },
  { value: "dance", label: "رقصیدن" },
  { value: "documentary", label: "مستند" },
  { value: "drama", label: "درام" },
  { value: "education", label: "آموزشی" },
  { value: "entertainment", label: "سرگرمی" },
  { value: "family", label: "خانوادگی" },
  { value: "fantasy", label: "فانتزی" },
  { value: "history", label: "تاریخی" },
  { value: "horror", label: "ترسناک" },
  { value: "independent", label: "مستقل" },
  { value: "international", label: "بین المللی" },
  { value: "kids", label: "کودکانه" },
  { value: "kids & family", label: "کودکانه و خانوادگی" },
  { value: "medical", label: "پزشکی" },
  { value: "military/war", label: "نظامی/جنگی" },
  { value: "music", label: "موسیقی" },
  { value: "musical", label: "موزیکال" },
  { value: "mystery/crime", label: "رمز و راز / جنایی" },
  { value: "nature", label: "طبیعت" },
  { value: "paranormal", label: "ماوراء الطبیعه" },
  { value: "politics", label: "سیاسی" },
  { value: "racing", label: "مسابقه" },
  { value: "romance", label: "داستان عاشقانه" },
  { value: "sci-fi/horror", label: "علمی تخیلی / ترسناک" },
  { value: "science", label: "علوم پایه" },
  { value: "science fiction", label: "علمی تخیلی" },
  { value: "science/nature", label: "علم/طبیعت" },
  { value: "spanish", label: "اسپانیایی" },
  { value: "travel", label: "مسافرت رفتن" },
  { value: "western", label: "غربی" },
];

export const optionsQuality = [
  { value: "hd 1080", label: "HD 1080" },
  { value: "hd 720", label: "HD 720" },
  { value: "dvd", label: "DVD" },
  { value: "ts", label: "TS" },
];
